# Generated by Django 5.1.7 on 2025-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropDiseaseDetection', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
